[Matrix] change to new C++ PVR interface way
janbar/pvr.mythtv pull request #152
Opened 2020-06-06 18:28 UTC by AlwinEsch

Changes related to xbmc/xbmc#16485.

This make the addon to the new C++ addon interface.

Runtime test was OK.

Hope is mostly OK :smile: this is one of the biggest PVR addons :v:, specially with setting value get is now different to before.

2020-06-06 21:01 UTC, janbar commented
@AlwinEsch  GREAT WORK !
I will test it soon.

2020-06-07 10:13 UTC, janbar requested changes
I am testing it. For now I found a little typo in settings.cpp.

2020-06-07 10:13 UTC, janbar commented on src/settings.cpp
> +    kodi::Log(ADDON_LOG_ERROR, "Couldn't get 'recordinm_icons' setting, falling back to '%u' as default", DEFAULT_RECORDING_ICONS);
recordinm_icons  --> recording_icons

2020-06-07 10:13 UTC, janbar commented on src/settings.cpp
> +    if (m_bRecordingIcons != settingValue.GetBoolean())
recordinm_icons --> recording_icons

2020-06-07 16:29 UTC, janbar commented
IMO it is OK, and ready to merge after fixing the typo.

2020-06-07 16:33 UTC, AlwinEsch commented
May still take a little while to come in. I am not at home for the next few weeks and will also look through all the addons beforehand.

2020-06-07 16:37 UTC, janbar commented
I have one issue when I open the box to edit a timer: The type isn't right and it always show "Record manual" instead the real type of the timer. Opening the list to edit it, the selected value is right, so I guess the PVR misses to initialize the right value on opening the editing box.

![Capture d’écran du 2020-06-07 18-07-10](https://user-images.githubusercontent.com/2353635/83974426-84fb5200-a8ed-11ea-94a1-16826b62455e.png)
![Capture d’écran du 2020-06-07 18-08-14](https://user-images.githubusercontent.com/2353635/83974431-8c226000-a8ed-11ea-8152-da3b8fec0635.png)

@ksooo, It isn't related to this change, but I catch this bug when testing this.

2020-06-07 16:51 UTC, janbar commented
@AlwinEsch , thanks for your work. We have a nice API now. Hope it will be accepted as soon as possible.

2020-06-11 15:27 UTC, AlwinEsch commented
Have fixed the typo and after all addons are ready can it in.

2020-06-13 13:40 UTC, merged

2020-06-13 14:22 UTC, ksooo commented
> @ksooo, It isn't related to this change, but I catch this bug when testing this.

 I think this is fixed by https://github.com/xbmc/xbmc/pull/18027

2020-06-13 14:50 UTC, janbar commented
Thanks @ksooo !

What else, the new API is really a great improvement and that will fix all mistakes we could make using directly C structs. Nice.